[2022-08-21 12:35:46,645] {processor.py:163} INFO - Started process (PID=72626) to work on /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
[2022-08-21 12:35:46,645] {processor.py:620} INFO - Processing file /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2022-08-21 12:35:46,645] {logging_mixin.py:109} INFO - [2022-08-21 12:35:46,645] {dagbag.py:500} INFO - Filling up the DagBag from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
[2022-08-21 12:35:46,653] {logging_mixin.py:109} INFO - [2022-08-21 12:35:46,652] {dagbag.py:334} ERROR - Failed to import: /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2022-08-21 12:35:46,662] {processor.py:634} WARNING - No viable dags retrieved from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
[2022-08-21 12:35:46,669] {processor.py:171} INFO - Processing /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py took 0.026 seconds
[2022-08-21 12:36:22,204] {processor.py:163} INFO - Started process (PID=72661) to work on /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
[2022-08-21 12:36:22,205] {processor.py:620} INFO - Processing file /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2022-08-21 12:36:22,205] {logging_mixin.py:109} INFO - [2022-08-21 12:36:22,205] {dagbag.py:500} INFO - Filling up the DagBag from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
[2022-08-21 12:36:22,213] {logging_mixin.py:109} INFO - [2022-08-21 12:36:22,212] {dagbag.py:334} ERROR - Failed to import: /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2022-08-21 12:36:22,220] {processor.py:634} WARNING - No viable dags retrieved from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
[2022-08-21 12:36:22,228] {processor.py:171} INFO - Processing /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py took 0.026 seconds
[2022-08-21 12:37:43,475] {processor.py:163} INFO - Started process (PID=73029) to work on /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
[2022-08-21 12:37:43,476] {processor.py:620} INFO - Processing file /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2022-08-21 12:37:43,477] {logging_mixin.py:109} INFO - [2022-08-21 12:37:43,477] {dagbag.py:500} INFO - Filling up the DagBag from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
[2022-08-21 12:37:43,484] {logging_mixin.py:109} INFO - [2022-08-21 12:37:43,483] {dagbag.py:334} ERROR - Failed to import: /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2022-08-21 12:37:43,492] {processor.py:634} WARNING - No viable dags retrieved from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
[2022-08-21 12:37:43,499] {processor.py:171} INFO - Processing /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py took 0.026 seconds
[2022-08-21 12:38:19,031] {processor.py:163} INFO - Started process (PID=73114) to work on /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
[2022-08-21 12:38:19,032] {processor.py:620} INFO - Processing file /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2022-08-21 12:38:19,032] {logging_mixin.py:109} INFO - [2022-08-21 12:38:19,032] {dagbag.py:500} INFO - Filling up the DagBag from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
[2022-08-21 12:38:19,040] {logging_mixin.py:109} INFO - [2022-08-21 12:38:19,039] {dagbag.py:334} ERROR - Failed to import: /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2022-08-21 12:38:19,049] {processor.py:634} WARNING - No viable dags retrieved from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
[2022-08-21 12:38:19,057] {processor.py:171} INFO - Processing /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py took 0.028 seconds
[2022-08-21 12:38:54,548] {processor.py:163} INFO - Started process (PID=73207) to work on /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
[2022-08-21 12:38:54,548] {processor.py:620} INFO - Processing file /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2022-08-21 12:38:54,549] {logging_mixin.py:109} INFO - [2022-08-21 12:38:54,549] {dagbag.py:500} INFO - Filling up the DagBag from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
[2022-08-21 12:38:54,556] {logging_mixin.py:109} INFO - [2022-08-21 12:38:54,555] {dagbag.py:334} ERROR - Failed to import: /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2022-08-21 12:38:54,565] {processor.py:634} WARNING - No viable dags retrieved from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
[2022-08-21 12:38:54,572] {processor.py:171} INFO - Processing /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py took 0.026 seconds
[2022-08-21 12:39:30,673] {processor.py:163} INFO - Started process (PID=73242) to work on /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
[2022-08-21 12:39:30,674] {processor.py:620} INFO - Processing file /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2022-08-21 12:39:30,674] {logging_mixin.py:109} INFO - [2022-08-21 12:39:30,674] {dagbag.py:500} INFO - Filling up the DagBag from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
[2022-08-21 12:39:30,681] {logging_mixin.py:109} INFO - [2022-08-21 12:39:30,680] {dagbag.py:334} ERROR - Failed to import: /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2022-08-21 12:39:30,689] {processor.py:634} WARNING - No viable dags retrieved from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
[2022-08-21 12:39:30,698] {processor.py:171} INFO - Processing /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py took 0.027 seconds
[2022-08-21 12:40:06,737] {processor.py:163} INFO - Started process (PID=73277) to work on /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
[2022-08-21 12:40:06,737] {processor.py:620} INFO - Processing file /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2022-08-21 12:40:06,738] {logging_mixin.py:109} INFO - [2022-08-21 12:40:06,738] {dagbag.py:500} INFO - Filling up the DagBag from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
[2022-08-21 12:40:06,745] {logging_mixin.py:109} INFO - [2022-08-21 12:40:06,744] {dagbag.py:334} ERROR - Failed to import: /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2022-08-21 12:40:06,753] {processor.py:634} WARNING - No viable dags retrieved from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
[2022-08-21 12:40:06,762] {processor.py:171} INFO - Processing /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py took 0.027 seconds
[2022-08-21 12:40:41,916] {processor.py:163} INFO - Started process (PID=73346) to work on /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
[2022-08-21 12:40:41,917] {processor.py:620} INFO - Processing file /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2022-08-21 12:40:41,917] {logging_mixin.py:109} INFO - [2022-08-21 12:40:41,917] {dagbag.py:500} INFO - Filling up the DagBag from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
[2022-08-21 12:40:41,924] {logging_mixin.py:109} INFO - [2022-08-21 12:40:41,923] {dagbag.py:334} ERROR - Failed to import: /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2022-08-21 12:40:41,933] {processor.py:634} WARNING - No viable dags retrieved from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
[2022-08-21 12:40:41,941] {processor.py:171} INFO - Processing /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py took 0.027 seconds
[2022-08-21 12:41:18,750] {processor.py:163} INFO - Started process (PID=73443) to work on /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
[2022-08-21 12:41:18,751] {processor.py:620} INFO - Processing file /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2022-08-21 12:41:18,751] {logging_mixin.py:109} INFO - [2022-08-21 12:41:18,751] {dagbag.py:500} INFO - Filling up the DagBag from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
[2022-08-21 12:41:18,763] {logging_mixin.py:109} INFO - [2022-08-21 12:41:18,761] {dagbag.py:334} ERROR - Failed to import: /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2022-08-21 12:41:18,776] {processor.py:634} WARNING - No viable dags retrieved from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
[2022-08-21 12:41:18,787] {processor.py:171} INFO - Processing /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py took 0.039 seconds
[2022-08-21 12:41:54,944] {processor.py:163} INFO - Started process (PID=73502) to work on /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
[2022-08-21 12:41:54,945] {processor.py:620} INFO - Processing file /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2022-08-21 12:41:54,945] {logging_mixin.py:109} INFO - [2022-08-21 12:41:54,945] {dagbag.py:500} INFO - Filling up the DagBag from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
[2022-08-21 12:41:54,952] {logging_mixin.py:109} INFO - [2022-08-21 12:41:54,951] {dagbag.py:334} ERROR - Failed to import: /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2022-08-21 12:41:54,961] {processor.py:634} WARNING - No viable dags retrieved from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
[2022-08-21 12:41:54,969] {processor.py:171} INFO - Processing /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py took 0.028 seconds
[2022-08-21 12:42:32,776] {processor.py:163} INFO - Started process (PID=73674) to work on /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
[2022-08-21 12:42:32,777] {processor.py:620} INFO - Processing file /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2022-08-21 12:42:32,777] {logging_mixin.py:109} INFO - [2022-08-21 12:42:32,777] {dagbag.py:500} INFO - Filling up the DagBag from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
[2022-08-21 12:42:32,785] {logging_mixin.py:109} INFO - [2022-08-21 12:42:32,784] {dagbag.py:334} ERROR - Failed to import: /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2022-08-21 12:42:32,793] {processor.py:634} WARNING - No viable dags retrieved from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
[2022-08-21 12:42:32,800] {processor.py:171} INFO - Processing /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py took 0.026 seconds
[2022-08-21 12:43:09,487] {processor.py:163} INFO - Started process (PID=73770) to work on /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
[2022-08-21 12:43:09,488] {processor.py:620} INFO - Processing file /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2022-08-21 12:43:09,488] {logging_mixin.py:109} INFO - [2022-08-21 12:43:09,488] {dagbag.py:500} INFO - Filling up the DagBag from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
[2022-08-21 12:43:09,496] {logging_mixin.py:109} INFO - [2022-08-21 12:43:09,495] {dagbag.py:334} ERROR - Failed to import: /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2022-08-21 12:43:09,507] {processor.py:634} WARNING - No viable dags retrieved from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
[2022-08-21 12:43:09,515] {processor.py:171} INFO - Processing /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py took 0.030 seconds
[2022-08-21 12:43:46,777] {processor.py:163} INFO - Started process (PID=73926) to work on /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
[2022-08-21 12:43:46,785] {processor.py:620} INFO - Processing file /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2022-08-21 12:43:46,787] {logging_mixin.py:109} INFO - [2022-08-21 12:43:46,786] {dagbag.py:500} INFO - Filling up the DagBag from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
[2022-08-21 12:43:46,843] {logging_mixin.py:109} INFO - [2022-08-21 12:43:46,841] {dagbag.py:334} ERROR - Failed to import: /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2022-08-21 12:43:46,926] {processor.py:634} WARNING - No viable dags retrieved from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
[2022-08-21 12:43:46,972] {processor.py:171} INFO - Processing /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py took 0.215 seconds
[2022-08-21 12:44:29,712] {processor.py:163} INFO - Started process (PID=74165) to work on /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
[2022-08-21 12:44:29,713] {processor.py:620} INFO - Processing file /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2022-08-21 12:44:29,713] {logging_mixin.py:109} INFO - [2022-08-21 12:44:29,713] {dagbag.py:500} INFO - Filling up the DagBag from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
[2022-08-21 12:44:29,721] {logging_mixin.py:109} INFO - [2022-08-21 12:44:29,720] {dagbag.py:334} ERROR - Failed to import: /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2022-08-21 12:44:29,728] {processor.py:634} WARNING - No viable dags retrieved from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
[2022-08-21 12:44:29,738] {processor.py:171} INFO - Processing /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py took 0.027 seconds
[2022-08-21 12:45:06,138] {processor.py:163} INFO - Started process (PID=74266) to work on /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
[2022-08-21 12:45:06,139] {processor.py:620} INFO - Processing file /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2022-08-21 12:45:06,139] {logging_mixin.py:109} INFO - [2022-08-21 12:45:06,139] {dagbag.py:500} INFO - Filling up the DagBag from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
[2022-08-21 12:45:06,147] {logging_mixin.py:109} INFO - [2022-08-21 12:45:06,146] {dagbag.py:334} ERROR - Failed to import: /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2022-08-21 12:45:06,155] {processor.py:634} WARNING - No viable dags retrieved from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
[2022-08-21 12:45:06,164] {processor.py:171} INFO - Processing /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py took 0.028 seconds
[2022-08-21 12:45:42,241] {processor.py:163} INFO - Started process (PID=74745) to work on /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
[2022-08-21 12:45:42,241] {processor.py:620} INFO - Processing file /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2022-08-21 12:45:42,242] {logging_mixin.py:109} INFO - [2022-08-21 12:45:42,241] {dagbag.py:500} INFO - Filling up the DagBag from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
[2022-08-21 12:45:42,260] {processor.py:632} INFO - DAG(s) dict_keys(['example_python_operator']) retrieved from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py
[2022-08-21 12:45:42,264] {logging_mixin.py:109} WARNING - /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/serialized_dag.py:120 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2022-08-21 12:45:42,937] {logging_mixin.py:109} INFO - [2022-08-21 12:45:42,937] {manager.py:496} INFO - Created Permission View: can read on DAG:example_python_operator
[2022-08-21 12:45:42,946] {logging_mixin.py:109} INFO - [2022-08-21 12:45:42,946] {manager.py:496} INFO - Created Permission View: can edit on DAG:example_python_operator
[2022-08-21 12:45:42,947] {logging_mixin.py:109} INFO - [2022-08-21 12:45:42,946] {dag.py:2389} INFO - Sync 1 DAGs
[2022-08-21 12:45:42,953] {logging_mixin.py:109} INFO - [2022-08-21 12:45:42,953] {dag.py:2408} INFO - Creating ORM DAG for example_python_operator
[2022-08-21 12:45:42,957] {logging_mixin.py:109} WARNING - /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py:2426 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2022-08-21 12:45:42,961] {logging_mixin.py:109} INFO - [2022-08-21 12:45:42,961] {dag.py:2914} INFO - Setting next_dagrun for example_python_operator to None
[2022-08-21 12:45:42,979] {processor.py:171} INFO - Processing /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/example_python_operator.py took 0.741 seconds
