[2022-08-21 12:35:31,164] {processor.py:163} INFO - Started process (PID=72527) to work on /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-08-21 12:35:31,164] {processor.py:620} INFO - Processing file /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2022-08-21 12:35:31,165] {logging_mixin.py:109} INFO - [2022-08-21 12:35:31,164] {dagbag.py:500} INFO - Filling up the DagBag from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-08-21 12:35:31,173] {logging_mixin.py:109} INFO - [2022-08-21 12:35:31,172] {dagbag.py:334} ERROR - Failed to import: /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 81, in <module>
    tutorial_etl_dag = tutorial_taskflow_api_etl_virtualenv()
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 2963, in factory
    f(**f_kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 76, in tutorial_taskflow_api_etl_virtualenv
    order_data = extract()
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 219, in factory
    op = decorated_operator_class(
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/decorators/python_virtualenv.py", line 61, in __init__
    super().__init__(kwargs_to_upstream=kwargs_to_upstream, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 131, in __init__
    super().__init__(**kwargs_to_upstream, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2022-08-21 12:35:31,181] {processor.py:634} WARNING - No viable dags retrieved from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-08-21 12:35:31,189] {processor.py:171} INFO - Processing /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.028 seconds
[2022-08-21 12:36:06,425] {processor.py:163} INFO - Started process (PID=72645) to work on /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-08-21 12:36:06,425] {processor.py:620} INFO - Processing file /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2022-08-21 12:36:06,426] {logging_mixin.py:109} INFO - [2022-08-21 12:36:06,426] {dagbag.py:500} INFO - Filling up the DagBag from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-08-21 12:36:06,434] {logging_mixin.py:109} INFO - [2022-08-21 12:36:06,433] {dagbag.py:334} ERROR - Failed to import: /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 81, in <module>
    tutorial_etl_dag = tutorial_taskflow_api_etl_virtualenv()
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 2963, in factory
    f(**f_kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 76, in tutorial_taskflow_api_etl_virtualenv
    order_data = extract()
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 219, in factory
    op = decorated_operator_class(
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/decorators/python_virtualenv.py", line 61, in __init__
    super().__init__(kwargs_to_upstream=kwargs_to_upstream, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 131, in __init__
    super().__init__(**kwargs_to_upstream, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2022-08-21 12:36:06,443] {processor.py:634} WARNING - No viable dags retrieved from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-08-21 12:36:06,450] {processor.py:171} INFO - Processing /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.027 seconds
[2022-08-21 12:36:42,558] {processor.py:163} INFO - Started process (PID=72679) to work on /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-08-21 12:36:42,558] {processor.py:620} INFO - Processing file /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2022-08-21 12:36:42,559] {logging_mixin.py:109} INFO - [2022-08-21 12:36:42,559] {dagbag.py:500} INFO - Filling up the DagBag from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-08-21 12:36:42,568] {logging_mixin.py:109} INFO - [2022-08-21 12:36:42,566] {dagbag.py:334} ERROR - Failed to import: /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 81, in <module>
    tutorial_etl_dag = tutorial_taskflow_api_etl_virtualenv()
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 2963, in factory
    f(**f_kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 76, in tutorial_taskflow_api_etl_virtualenv
    order_data = extract()
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 219, in factory
    op = decorated_operator_class(
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/decorators/python_virtualenv.py", line 61, in __init__
    super().__init__(kwargs_to_upstream=kwargs_to_upstream, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 131, in __init__
    super().__init__(**kwargs_to_upstream, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2022-08-21 12:36:42,575] {processor.py:634} WARNING - No viable dags retrieved from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-08-21 12:36:42,583] {processor.py:171} INFO - Processing /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.027 seconds
[2022-08-21 12:37:28,021] {processor.py:163} INFO - Started process (PID=72966) to work on /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-08-21 12:37:28,022] {processor.py:620} INFO - Processing file /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2022-08-21 12:37:28,022] {logging_mixin.py:109} INFO - [2022-08-21 12:37:28,022] {dagbag.py:500} INFO - Filling up the DagBag from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-08-21 12:37:28,031] {logging_mixin.py:109} INFO - [2022-08-21 12:37:28,029] {dagbag.py:334} ERROR - Failed to import: /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 81, in <module>
    tutorial_etl_dag = tutorial_taskflow_api_etl_virtualenv()
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 2963, in factory
    f(**f_kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 76, in tutorial_taskflow_api_etl_virtualenv
    order_data = extract()
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 219, in factory
    op = decorated_operator_class(
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/decorators/python_virtualenv.py", line 61, in __init__
    super().__init__(kwargs_to_upstream=kwargs_to_upstream, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 131, in __init__
    super().__init__(**kwargs_to_upstream, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2022-08-21 12:37:28,039] {processor.py:634} WARNING - No viable dags retrieved from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-08-21 12:37:28,047] {processor.py:171} INFO - Processing /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.028 seconds
[2022-08-21 12:38:03,254] {processor.py:163} INFO - Started process (PID=73098) to work on /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-08-21 12:38:03,254] {processor.py:620} INFO - Processing file /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2022-08-21 12:38:03,255] {logging_mixin.py:109} INFO - [2022-08-21 12:38:03,255] {dagbag.py:500} INFO - Filling up the DagBag from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-08-21 12:38:03,263] {logging_mixin.py:109} INFO - [2022-08-21 12:38:03,262] {dagbag.py:334} ERROR - Failed to import: /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 81, in <module>
    tutorial_etl_dag = tutorial_taskflow_api_etl_virtualenv()
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 2963, in factory
    f(**f_kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 76, in tutorial_taskflow_api_etl_virtualenv
    order_data = extract()
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 219, in factory
    op = decorated_operator_class(
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/decorators/python_virtualenv.py", line 61, in __init__
    super().__init__(kwargs_to_upstream=kwargs_to_upstream, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 131, in __init__
    super().__init__(**kwargs_to_upstream, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2022-08-21 12:38:03,272] {processor.py:634} WARNING - No viable dags retrieved from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-08-21 12:38:03,279] {processor.py:171} INFO - Processing /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.028 seconds
[2022-08-21 12:38:39,382] {processor.py:163} INFO - Started process (PID=73132) to work on /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-08-21 12:38:39,383] {processor.py:620} INFO - Processing file /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2022-08-21 12:38:39,383] {logging_mixin.py:109} INFO - [2022-08-21 12:38:39,383] {dagbag.py:500} INFO - Filling up the DagBag from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-08-21 12:38:39,392] {logging_mixin.py:109} INFO - [2022-08-21 12:38:39,391] {dagbag.py:334} ERROR - Failed to import: /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 81, in <module>
    tutorial_etl_dag = tutorial_taskflow_api_etl_virtualenv()
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 2963, in factory
    f(**f_kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 76, in tutorial_taskflow_api_etl_virtualenv
    order_data = extract()
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 219, in factory
    op = decorated_operator_class(
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/decorators/python_virtualenv.py", line 61, in __init__
    super().__init__(kwargs_to_upstream=kwargs_to_upstream, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 131, in __init__
    super().__init__(**kwargs_to_upstream, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2022-08-21 12:38:39,400] {processor.py:634} WARNING - No viable dags retrieved from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-08-21 12:38:39,408] {processor.py:171} INFO - Processing /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.028 seconds
[2022-08-21 12:39:14,064] {processor.py:163} INFO - Started process (PID=73226) to work on /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-08-21 12:39:14,064] {processor.py:620} INFO - Processing file /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2022-08-21 12:39:14,065] {logging_mixin.py:109} INFO - [2022-08-21 12:39:14,065] {dagbag.py:500} INFO - Filling up the DagBag from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-08-21 12:39:14,073] {logging_mixin.py:109} INFO - [2022-08-21 12:39:14,072] {dagbag.py:334} ERROR - Failed to import: /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 81, in <module>
    tutorial_etl_dag = tutorial_taskflow_api_etl_virtualenv()
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 2963, in factory
    f(**f_kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 76, in tutorial_taskflow_api_etl_virtualenv
    order_data = extract()
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 219, in factory
    op = decorated_operator_class(
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/decorators/python_virtualenv.py", line 61, in __init__
    super().__init__(kwargs_to_upstream=kwargs_to_upstream, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 131, in __init__
    super().__init__(**kwargs_to_upstream, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2022-08-21 12:39:14,082] {processor.py:634} WARNING - No viable dags retrieved from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-08-21 12:39:14,091] {processor.py:171} INFO - Processing /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.030 seconds
[2022-08-21 12:39:49,002] {processor.py:163} INFO - Started process (PID=73259) to work on /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-08-21 12:39:49,003] {processor.py:620} INFO - Processing file /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2022-08-21 12:39:49,003] {logging_mixin.py:109} INFO - [2022-08-21 12:39:49,003] {dagbag.py:500} INFO - Filling up the DagBag from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-08-21 12:39:49,013] {logging_mixin.py:109} INFO - [2022-08-21 12:39:49,011] {dagbag.py:334} ERROR - Failed to import: /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 81, in <module>
    tutorial_etl_dag = tutorial_taskflow_api_etl_virtualenv()
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 2963, in factory
    f(**f_kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 76, in tutorial_taskflow_api_etl_virtualenv
    order_data = extract()
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 219, in factory
    op = decorated_operator_class(
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/decorators/python_virtualenv.py", line 61, in __init__
    super().__init__(kwargs_to_upstream=kwargs_to_upstream, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 131, in __init__
    super().__init__(**kwargs_to_upstream, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2022-08-21 12:39:49,022] {processor.py:634} WARNING - No viable dags retrieved from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-08-21 12:39:49,031] {processor.py:171} INFO - Processing /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.030 seconds
[2022-08-21 12:40:23,034] {processor.py:163} INFO - Started process (PID=73293) to work on /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-08-21 12:40:23,035] {processor.py:620} INFO - Processing file /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2022-08-21 12:40:23,035] {logging_mixin.py:109} INFO - [2022-08-21 12:40:23,035] {dagbag.py:500} INFO - Filling up the DagBag from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-08-21 12:40:23,044] {logging_mixin.py:109} INFO - [2022-08-21 12:40:23,042] {dagbag.py:334} ERROR - Failed to import: /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 81, in <module>
    tutorial_etl_dag = tutorial_taskflow_api_etl_virtualenv()
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 2963, in factory
    f(**f_kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 76, in tutorial_taskflow_api_etl_virtualenv
    order_data = extract()
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 219, in factory
    op = decorated_operator_class(
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/decorators/python_virtualenv.py", line 61, in __init__
    super().__init__(kwargs_to_upstream=kwargs_to_upstream, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 131, in __init__
    super().__init__(**kwargs_to_upstream, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2022-08-21 12:40:23,051] {processor.py:634} WARNING - No viable dags retrieved from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-08-21 12:40:23,059] {processor.py:171} INFO - Processing /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.027 seconds
[2022-08-21 12:40:58,837] {processor.py:163} INFO - Started process (PID=73374) to work on /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-08-21 12:40:58,838] {processor.py:620} INFO - Processing file /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2022-08-21 12:40:58,838] {logging_mixin.py:109} INFO - [2022-08-21 12:40:58,838] {dagbag.py:500} INFO - Filling up the DagBag from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-08-21 12:40:58,847] {logging_mixin.py:109} INFO - [2022-08-21 12:40:58,846] {dagbag.py:334} ERROR - Failed to import: /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 81, in <module>
    tutorial_etl_dag = tutorial_taskflow_api_etl_virtualenv()
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 2963, in factory
    f(**f_kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 76, in tutorial_taskflow_api_etl_virtualenv
    order_data = extract()
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 219, in factory
    op = decorated_operator_class(
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/decorators/python_virtualenv.py", line 61, in __init__
    super().__init__(kwargs_to_upstream=kwargs_to_upstream, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 131, in __init__
    super().__init__(**kwargs_to_upstream, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2022-08-21 12:40:58,856] {processor.py:634} WARNING - No viable dags retrieved from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-08-21 12:40:58,863] {processor.py:171} INFO - Processing /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.028 seconds
[2022-08-21 12:41:33,720] {processor.py:163} INFO - Started process (PID=73481) to work on /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-08-21 12:41:33,720] {processor.py:620} INFO - Processing file /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2022-08-21 12:41:33,721] {logging_mixin.py:109} INFO - [2022-08-21 12:41:33,721] {dagbag.py:500} INFO - Filling up the DagBag from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-08-21 12:41:33,730] {logging_mixin.py:109} INFO - [2022-08-21 12:41:33,728] {dagbag.py:334} ERROR - Failed to import: /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 81, in <module>
    tutorial_etl_dag = tutorial_taskflow_api_etl_virtualenv()
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 2963, in factory
    f(**f_kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 76, in tutorial_taskflow_api_etl_virtualenv
    order_data = extract()
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 219, in factory
    op = decorated_operator_class(
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/decorators/python_virtualenv.py", line 61, in __init__
    super().__init__(kwargs_to_upstream=kwargs_to_upstream, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 131, in __init__
    super().__init__(**kwargs_to_upstream, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2022-08-21 12:41:33,739] {processor.py:634} WARNING - No viable dags retrieved from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-08-21 12:41:33,747] {processor.py:171} INFO - Processing /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.030 seconds
[2022-08-21 12:42:08,820] {processor.py:163} INFO - Started process (PID=73517) to work on /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-08-21 12:42:08,820] {processor.py:620} INFO - Processing file /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2022-08-21 12:42:08,821] {logging_mixin.py:109} INFO - [2022-08-21 12:42:08,821] {dagbag.py:500} INFO - Filling up the DagBag from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-08-21 12:42:08,829] {logging_mixin.py:109} INFO - [2022-08-21 12:42:08,828] {dagbag.py:334} ERROR - Failed to import: /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 81, in <module>
    tutorial_etl_dag = tutorial_taskflow_api_etl_virtualenv()
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 2963, in factory
    f(**f_kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 76, in tutorial_taskflow_api_etl_virtualenv
    order_data = extract()
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 219, in factory
    op = decorated_operator_class(
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/decorators/python_virtualenv.py", line 61, in __init__
    super().__init__(kwargs_to_upstream=kwargs_to_upstream, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 131, in __init__
    super().__init__(**kwargs_to_upstream, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2022-08-21 12:42:08,837] {processor.py:634} WARNING - No viable dags retrieved from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-08-21 12:42:08,845] {processor.py:171} INFO - Processing /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.028 seconds
[2022-08-21 12:42:44,527] {processor.py:163} INFO - Started process (PID=73685) to work on /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-08-21 12:42:44,528] {processor.py:620} INFO - Processing file /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2022-08-21 12:42:44,528] {logging_mixin.py:109} INFO - [2022-08-21 12:42:44,528] {dagbag.py:500} INFO - Filling up the DagBag from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-08-21 12:42:44,537] {logging_mixin.py:109} INFO - [2022-08-21 12:42:44,536] {dagbag.py:334} ERROR - Failed to import: /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 81, in <module>
    tutorial_etl_dag = tutorial_taskflow_api_etl_virtualenv()
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 2963, in factory
    f(**f_kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 76, in tutorial_taskflow_api_etl_virtualenv
    order_data = extract()
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 219, in factory
    op = decorated_operator_class(
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/decorators/python_virtualenv.py", line 61, in __init__
    super().__init__(kwargs_to_upstream=kwargs_to_upstream, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 131, in __init__
    super().__init__(**kwargs_to_upstream, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2022-08-21 12:42:44,546] {processor.py:634} WARNING - No viable dags retrieved from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-08-21 12:42:44,554] {processor.py:171} INFO - Processing /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.028 seconds
[2022-08-21 12:43:18,350] {processor.py:163} INFO - Started process (PID=73779) to work on /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-08-21 12:43:18,351] {processor.py:620} INFO - Processing file /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2022-08-21 12:43:18,351] {logging_mixin.py:109} INFO - [2022-08-21 12:43:18,351] {dagbag.py:500} INFO - Filling up the DagBag from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-08-21 12:43:18,360] {logging_mixin.py:109} INFO - [2022-08-21 12:43:18,358] {dagbag.py:334} ERROR - Failed to import: /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 81, in <module>
    tutorial_etl_dag = tutorial_taskflow_api_etl_virtualenv()
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 2963, in factory
    f(**f_kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 76, in tutorial_taskflow_api_etl_virtualenv
    order_data = extract()
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 219, in factory
    op = decorated_operator_class(
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/decorators/python_virtualenv.py", line 61, in __init__
    super().__init__(kwargs_to_upstream=kwargs_to_upstream, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 131, in __init__
    super().__init__(**kwargs_to_upstream, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2022-08-21 12:43:18,368] {processor.py:634} WARNING - No viable dags retrieved from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-08-21 12:43:18,376] {processor.py:171} INFO - Processing /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.028 seconds
[2022-08-21 12:43:51,153] {processor.py:163} INFO - Started process (PID=73975) to work on /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-08-21 12:43:51,153] {processor.py:620} INFO - Processing file /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2022-08-21 12:43:51,154] {logging_mixin.py:109} INFO - [2022-08-21 12:43:51,154] {dagbag.py:500} INFO - Filling up the DagBag from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-08-21 12:43:51,163] {logging_mixin.py:109} INFO - [2022-08-21 12:43:51,161] {dagbag.py:334} ERROR - Failed to import: /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 81, in <module>
    tutorial_etl_dag = tutorial_taskflow_api_etl_virtualenv()
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 2963, in factory
    f(**f_kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 76, in tutorial_taskflow_api_etl_virtualenv
    order_data = extract()
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 219, in factory
    op = decorated_operator_class(
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/decorators/python_virtualenv.py", line 61, in __init__
    super().__init__(kwargs_to_upstream=kwargs_to_upstream, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 131, in __init__
    super().__init__(**kwargs_to_upstream, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2022-08-21 12:43:51,172] {processor.py:634} WARNING - No viable dags retrieved from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-08-21 12:43:51,180] {processor.py:171} INFO - Processing /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.029 seconds
[2022-08-21 12:44:29,138] {processor.py:163} INFO - Started process (PID=74164) to work on /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-08-21 12:44:29,138] {processor.py:620} INFO - Processing file /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2022-08-21 12:44:29,139] {logging_mixin.py:109} INFO - [2022-08-21 12:44:29,139] {dagbag.py:500} INFO - Filling up the DagBag from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-08-21 12:44:29,147] {logging_mixin.py:109} INFO - [2022-08-21 12:44:29,146] {dagbag.py:334} ERROR - Failed to import: /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 81, in <module>
    tutorial_etl_dag = tutorial_taskflow_api_etl_virtualenv()
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 2963, in factory
    f(**f_kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 76, in tutorial_taskflow_api_etl_virtualenv
    order_data = extract()
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 219, in factory
    op = decorated_operator_class(
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/decorators/python_virtualenv.py", line 61, in __init__
    super().__init__(kwargs_to_upstream=kwargs_to_upstream, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 131, in __init__
    super().__init__(**kwargs_to_upstream, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2022-08-21 12:44:29,156] {processor.py:634} WARNING - No viable dags retrieved from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-08-21 12:44:29,164] {processor.py:171} INFO - Processing /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.028 seconds
[2022-08-21 12:45:05,579] {processor.py:163} INFO - Started process (PID=74265) to work on /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-08-21 12:45:05,580] {processor.py:620} INFO - Processing file /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2022-08-21 12:45:05,580] {logging_mixin.py:109} INFO - [2022-08-21 12:45:05,580] {dagbag.py:500} INFO - Filling up the DagBag from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-08-21 12:45:05,589] {logging_mixin.py:109} INFO - [2022-08-21 12:45:05,587] {dagbag.py:334} ERROR - Failed to import: /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 81, in <module>
    tutorial_etl_dag = tutorial_taskflow_api_etl_virtualenv()
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py", line 2963, in factory
    f(**f_kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py", line 76, in tutorial_taskflow_api_etl_virtualenv
    order_data = extract()
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 219, in factory
    op = decorated_operator_class(
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/decorators/python_virtualenv.py", line 61, in __init__
    super().__init__(kwargs_to_upstream=kwargs_to_upstream, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/decorators/base.py", line 131, in __init__
    super().__init__(**kwargs_to_upstream, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2022-08-21 12:45:05,598] {processor.py:634} WARNING - No viable dags retrieved from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-08-21 12:45:05,607] {processor.py:171} INFO - Processing /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.030 seconds
[2022-08-21 12:45:39,005] {processor.py:163} INFO - Started process (PID=74725) to work on /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-08-21 12:45:39,006] {processor.py:620} INFO - Processing file /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py for tasks to queue
[2022-08-21 12:45:39,006] {logging_mixin.py:109} INFO - [2022-08-21 12:45:39,006] {dagbag.py:500} INFO - Filling up the DagBag from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-08-21 12:45:39,027] {processor.py:632} INFO - DAG(s) dict_keys(['tutorial_taskflow_api_etl_virtualenv']) retrieved from /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py
[2022-08-21 12:45:39,031] {logging_mixin.py:109} WARNING - /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/serialized_dag.py:120 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2022-08-21 12:45:39,822] {logging_mixin.py:109} INFO - [2022-08-21 12:45:39,822] {manager.py:496} INFO - Created Permission View: can read on DAG:tutorial_taskflow_api_etl_virtualenv
[2022-08-21 12:45:39,831] {logging_mixin.py:109} INFO - [2022-08-21 12:45:39,831] {manager.py:496} INFO - Created Permission View: can edit on DAG:tutorial_taskflow_api_etl_virtualenv
[2022-08-21 12:45:39,832] {logging_mixin.py:109} INFO - [2022-08-21 12:45:39,831] {dag.py:2389} INFO - Sync 1 DAGs
[2022-08-21 12:45:39,838] {logging_mixin.py:109} INFO - [2022-08-21 12:45:39,838] {dag.py:2408} INFO - Creating ORM DAG for tutorial_taskflow_api_etl_virtualenv
[2022-08-21 12:45:39,842] {logging_mixin.py:109} WARNING - /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/models/dag.py:2426 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2022-08-21 12:45:39,846] {logging_mixin.py:109} INFO - [2022-08-21 12:45:39,846] {dag.py:2914} INFO - Setting next_dagrun for tutorial_taskflow_api_etl_virtualenv to None
[2022-08-21 12:45:39,863] {processor.py:171} INFO - Processing /home/ubuntu/anaconda3/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl_virtualenv.py took 0.860 seconds
